name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

permissions:
  contents: write  # Права на запись

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev

      - name: Install dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install boost

      - name: Configure with CMake
        run: |
          cmake -S . -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build the project
        run: |
          cmake --build build

      - name: Run tests
        run: |
          cmake --build build --target test

      - name: Create package
        run: |
          cmake --build build --target package

      - name: Delete existing release and tag if they exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.run_number }}" | jq -r '.id // empty')
          if [ -n "$RELEASE_ID" ]; then
            echo "Deleting existing release with ID $RELEASE_ID"
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          fi

          if git rev-parse -q --verify "refs/tags/${{ github.run_number }}"; then
            git tag -d ${{ github.run_number }}
            git push origin :refs/tags/${{ github.run_number }}
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Release Asset (macOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/helloworld-0.0.${{ github.run_number }}-Darwin.dmg
          asset_name: helloworld-0.0.${{ github.run_number }}-Darwin.dmg
          asset_content_type: application/x-apple-diskimage
